# Generated by Django 3.2.7 on 2021-10-14 12:40

import backend_blog_tube.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('blog_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=100)),
                ('upload_datetime', models.DateTimeField(auto_now=True)),
                ('discription', models.CharField(max_length=200, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('reviewers', models.JSONField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='signup_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('otp', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default=None, max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('join_datetime', models.DateTimeField(auto_now=True)),
                ('blogs_upload', models.IntegerField(default=0)),
                ('salt', models.CharField(default=backend_blog_tube.models.generate_salt, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_to_anonymus', models.BooleanField(choices=[(True, 'show to anonymus'), (False, "doesn't show to anonymus")], default=True)),
                ('email_to_anonymus', models.BooleanField(choices=[(True, 'show to anonymus'), (False, "doesn't show to anonymus")], default=True)),
                ('photo_to_follower', models.BooleanField(choices=[(True, 'show to followers'), (False, "doesn't show to followers")], default=True)),
                ('email_to_follower', models.BooleanField(choices=[(True, 'show to followers'), (False, "doesn't show to followers")], default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_blog_tube.users')),
            ],
        ),
        migrations.CreateModel(
            name='login_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_blog_tube.users')),
            ],
        ),
        migrations.CreateModel(
            name='followings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followings', models.JSONField(default='[]')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_blog_tube.users')),
            ],
        ),
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.JSONField(default='[]')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_blog_tube.users')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('comment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('upload_datetime', models.DateTimeField(auto_now=True)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_blog_tube.blogs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_blog_tube.users')),
            ],
        ),
        migrations.CreateModel(
            name='blogs_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_data', models.JSONField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_blog_tube.blogs')),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_blog_tube.users'),
        ),
    ]
