# Generated by Django 3.2.3 on 2021-06-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_blog_tube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
