# Generated by Django 3.2.4 on 2021-06-26 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_blog_tube', '0003_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_to_anonymus', models.BooleanField(choices=[('show to anonymus', True), ("doesn't show to anonymus", False)], default=True)),
                ('email_to_anonymus', models.BooleanField(choices=[('show to anonymus', True), ("doesn't show to anonymus", False)], default=True)),
                ('photo_to_follower', models.BooleanField(choices=[('show to followers', True), ("doesn't show to followers", False)], default=True)),
                ('email_to_follower', models.BooleanField(choices=[('show to followers', True), ("doesn't show to followers", False)], default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_blog_tube.users')),
            ],
        ),
        migrations.CreateModel(
            name='followings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followings', models.JSONField(default='[]')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_blog_tube.users')),
            ],
        ),
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.JSONField(default='[]')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_blog_tube.users')),
            ],
        ),
    ]
