# Generated by Django 3.2.7 on 2021-09-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_blog_tube', '0004_followers_followings_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email_to_anonymus',
            field=models.BooleanField(choices=[(True, 'show to anonymus'), (False, "doesn't show to anonymus")], default=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email_to_follower',
            field=models.BooleanField(choices=[(True, 'show to followers'), (False, "doesn't show to followers")], default=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='photo_to_anonymus',
            field=models.BooleanField(choices=[(True, 'show to anonymus'), (False, "doesn't show to anonymus")], default=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='photo_to_follower',
            field=models.BooleanField(choices=[(True, 'show to followers'), (False, "doesn't show to followers")], default=True),
        ),
    ]
