# Generated by Django 3.2.7 on 2021-09-05 15:46

import backend_blog_tube.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_blog_tube', '0005_auto_20210901_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='salt',
            field=models.CharField(default=backend_blog_tube.models.generate_salt, max_length=6),
        ),
    ]
