# Generated by Django 3.2.7 on 2021-09-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_blog_tube', '0006_users_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='discription',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
