# Generated by Django 3.2.7 on 2021-09-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_blog_tube', '0007_blogs_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply_at',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='reply_of',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
