# Generated by Django 3.2.7 on 2021-09-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_blog_tube', '0009_blogs_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='reviewers',
            field=models.JSONField(default='[]'),
        ),
    ]
