# Generated by Django 3.2.7 on 2021-09-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_blog_tube', '0011_alter_blogs_reviewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reply_at',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='reply_of',
        ),
    ]
