# Generated by Django 3.2.7 on 2021-09-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_blog_tube', '0012_auto_20210924_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(default='this is a comment', max_length=200),
            preserve_default=False,
        ),
    ]
