# Generated by Django 3.2.7 on 2021-09-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_blog_tube', '0014_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='upload_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='upload_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='join_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
